# Generated by Django 2.1.2 on 2018-11-06 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPerro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedormascota.EstadoPerro'),
        ),
    ]
