# Generated by Django 2.1.2 on 2018-11-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='misperris'),
        ),
    ]
