# Generated by Django 2.1.2 on 2018-11-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0002_auto_20181106_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.FileField(blank=True, null=True, upload_to='misperris/%Y/%m/$D/'),
        ),
    ]
