# Generated by Django 2.1.2 on 2018-11-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0003_auto_20181106_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%D/'),
            preserve_default=False,
        ),
    ]
