# Generated by Django 2.1.2 on 2018-11-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0004_auto_20181106_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(upload_to='perros'),
        ),
    ]
