# Generated by Django 2.1.2 on 2018-11-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0005_auto_20181106_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(upload_to='apps/mantenedormascota/foto/'),
        ),
    ]
