# Generated by Django 2.1.2 on 2018-11-07 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0006_auto_20181106_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/%Y-%m-%d/'),
        ),
    ]
