# Generated by Django 2.1.2 on 2018-11-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0007_auto_20181106_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='fotografia',
            field=models.ImageField(default='', upload_to='profile_pics/%Y-%m-%d/'),
            preserve_default=False,
        ),
    ]
