# Generated by Django 2.1.2 on 2018-11-07 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0008_auto_20181106_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mantenedormascota.EstadoPerro'),
            preserve_default=False,
        ),
    ]
