# Generated by Django 2.1.2 on 2018-11-07 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenedormascota', '0009_auto_20181106_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perro',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mantenedormascota.EstadoPerro'),
        ),
    ]
