# Generated by Django 2.1.2 on 2018-10-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Ciudad', models.PositiveSmallIntegerField()),
                ('Descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=20)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Raza_predominante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Raza', models.PositiveSmallIntegerField()),
                ('Descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Region', models.PositiveSmallIntegerField()),
                ('Descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_tipo_estado', models.PositiveSmallIntegerField()),
                ('Descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Vivienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_Tipo_Vivienda', models.PositiveSmallIntegerField()),
                ('Descripcion', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='perfil',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AddField(
            model_name='usuario',
            name='Apellido',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Correo',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Fecha_Nacimineto',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Fono',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Run',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perros',
            name='Estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.Tipo_estado'),
        ),
        migrations.AddField(
            model_name='perros',
            name='Raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.Raza_predominante'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.Region'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='Ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Index.Ciudad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Index.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='Tipo_Vivienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Index.Tipo_Vivienda'),
        ),
    ]
