# Generated by Django 2.1.2 on 2018-11-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0003_auto_20181103_1112'),
        ('Index', '0002_auto_20181104_1513'),
    ]

    operations = [
    ]
