# Generated by Django 2.1.2 on 2018-11-07 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Index', '0004_merge_20181107_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perros',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='perros',
            name='Raza',
        ),
        migrations.DeleteModel(
            name='Perros',
        ),
        migrations.DeleteModel(
            name='Raza_predominante',
        ),
        migrations.DeleteModel(
            name='Tipo_estado',
        ),
    ]
